### ISSUE TITLE
多看的刷豆支持多账号么？

### ISSUE THREAD

**Issue by RouJiANG-14** [KD-happy/KDCheckin#2]
青龙的具体变量如何设置？

**Comment by KD-happy** [comment]
任何一个都可以多账号签到

主要配置都是对cookie.yml的配置

```shell
cp /ql/repo/KD-happy_KDCheckin/Cookie.yml /ql/config/Cookie.yml
```

上面的玩意一定要执行，不然青龙配置文件中看不见

下面是配置了两个账号

```yml
# 多看阅读
DuoKan:
    send: 0
    cookies:
        - user:
            name: '用户1'
            # user_id, token, device_id, app_id
            cookie: '用户1的Cookie'
        - user:
            name: '用户2'
            # user_id, token, device_id, app_id
            cookie: '用户2的Cookie'
```

多看的cookie好像必须要用手机抓包的cookie，然后cookie的关键字都在cookie.yml写着
