### ISSUE TITLE
cookie填写

### ISSUE THREAD

**Issue by GD2021** [KD-happy/KDCheckin#5]
![image](https://user-images.githubusercontent.com/81171294/177008952-a734b4bb-b0e4-42cd-a21c-b5f61466ba0d.png)
您好，我没看明白cookie怎样填写，为什么有两个cookie，是多账号吗？ 用户名也要填吗？

**Comment by GD2021** [comment]
user、 name也要填吗？

**Comment by GD2021** [comment]
填cookies还是cookie？

**Comment by KD-happy** [comment]
```yaml
AcFun:
    send: 0
    cookies:
        - user: # 用户1
            name: 'xxxxx' # 用户1的名称
            # acPasstoken, auth_key
            cookie: 'xxxxxxxxxxxxxxxxxx' # 用户1的Cookie
        - user: # 用户2
            name: 'xxxxx'
            # acPasstoken, auth_key
            cookie: 'xxxxxxxx'
```

![image](https://user-images.githubusercontent.com/67636118/177019786-c8361c3e-78e7-487f-9e70-0c9e0cf47c25.png)

看懂了吧
